// Stage list.
//
// Made with tool/gen_levels.dart (options per stage in tool/stage_plan.txt):
// each layout is the one, among every position reachable from a random
// room, that needs the most door pushes from the kitchen door.
// test/levels_test.dart checks that every stage is solvable, that `par` is
// the true shortest solution, and that every gimmick on the map is used.
//
// Stage ids are saved in players' progress: never change or reuse them.
import 'level_model.dart';

export 'level_model.dart';

final List<Chapter> chapters = [
  Chapter(
    number: 1,
    id: 'basic',
    icon: 'door',
    titleJa: '一階の客間',
    titleEn: 'The Ground Floor',
    subJa: 'はじめての配達。ふすまは敷居にそって、押した向きにだけすべる。',
    subEn: 'First deliveries. Doors slide only along their tracks, the way you push them.',
    levels: [
      Level(id: 'f01', ja: 'はじめてのお座敷', en: 'The First Room', par: 7, map: [
        '#######',
        '#P....#',
        '#.....#',
        '#.....#',
        '#.#..A#',
        '#######',
      ], doors: ['h2,1,2', 'h1,2,2']),
      Level(id: 'f02', ja: 'すきま', en: 'A Narrow Gap', par: 9, map: [
        '#######',
        '#.....#',
        '#.#...#',
        '#P....#',
        '#....A#',
        '#######',
      ], doors: ['h1,4,3', 'h3,3,2', 'h2,1,2']),
      Level(id: 'f03', ja: '廊下の角', en: 'Round the Corner', par: 11, map: [
        '########',
        '#P.....#',
        '#....A.#',
        '#......#',
        '#.#....#',
        '########',
      ], doors: ['h2,3,2', 'v3,1,2', 'v6,2,2']),
      Level(id: 'f04', ja: '押し入れの前', en: 'By the Closet', par: 13, map: [
        '########',
        '#......#',
        '#..#...#',
        '#..#...#',
        '#..#...#',
        '#P....A#',
        '########',
      ], doors: ['v2,2,3', 'v4,3,3', 'h2,1,2', 'h2,5,2']),
      Level(id: 'f05', ja: 'ふた部屋', en: 'Two Rooms', par: 15, map: [
        '########',
        '#......#',
        '#...#..#',
        '#......#',
        '#.#...B#',
        '#P...A.#',
        '########',
      ], doors: ['v2,1,2', 'h2,3,2', 'h3,4,2', 'h3,5,2', 'v1,2,2']),
      Level(id: 'f06', ja: '行き止まり', en: 'Dead End', par: 16, map: [
        '#########',
        '#..#....#',
        '#.......#',
        '#.......#',
        '#.....A.#',
        '#P....#.#',
        '#########',
      ], doors: ['h3,2,2', 'h4,3,3', 'v3,4,2', 'v7,2,2', 'v2,2,2']),
      Level(id: 'f07', ja: '相席', en: 'Sharing a Table', par: 18, map: [
        '#########',
        '#P......#',
        '#....#A.#',
        '#....#..#',
        '#.......#',
        '#.##..B.#',
        '#.......#',
        '#########',
      ], doors: ['v7,3,2', 'h3,4,2', 'h2,3,2', 'v3,1,2', 'v1,3,2', 'h4,5,2']),
      Level(id: 'f08', ja: '奥座敷', en: 'The Inner Room', par: 20, map: [
        '#########',
        '#.......#',
        '#...##..#',
        '#.......#',
        '#.......#',
        '#P..#.#.#',
        '#.....A.#',
        '#########',
      ], doors: ['v5,4,2', 'h2,1,2', 'h5,1,2', 'v2,2,3', 'h2,6,2', 'h3,3,2']),
    ],
  ),
  Chapter(
    number: 2,
    id: 'pair',
    icon: 'pair',
    titleJa: '対のふすま',
    titleEn: 'Paired Doors',
    subJa: '同じ波の柄のふすまは、一緒にすべる。',
    subEn: 'Doors with the same wave crest slide together.',
    levels: [
      Level(id: 'f09', ja: '波の柄', en: 'Wave Crest', par: 10, map: [
        '#######',
        '#P....#',
        '#.....#',
        '#.#...#',
        '#...A.#',
        '#...#.#',
        '#######',
      ], doors: ['v5,1,3=a', 'v1,2,2=a', 'h2,2,3']),
      Level(id: 'f10', ja: 'そろって動く', en: 'In Step', par: 12, map: [
        '########',
        '#.....A#',
        '#..#...#',
        '#.#....#',
        '#P.....#',
        '#......#',
        '########',
      ], doors: ['v4,2,2', 'h3,1,2=a', 'h2,5,2=a', 'h2,4,2']),
      Level(id: 'f11', ja: '片方がつかえる', en: 'One Holds Back', par: 14, map: [
        '########',
        '#P.#...#',
        '#....#A#',
        '#......#',
        '#.#....#',
        '#......#',
        '########',
      ], doors: ['h5,1,2', 'h3,2,2', 'h2,5,2=a', 'h2,3,3=a']),
      Level(id: 'f12', ja: '二組のお客さん', en: 'Two Parties', par: 16, map: [
        '########',
        '#....B.#',
        '#......#',
        '#......#',
        '#......#',
        '#......#',
        '#P.#..A#',
        '########',
      ], doors: ['v2,4,2', 'h4,3,2=a', 'v3,1,2', 'v6,2,2', 'h4,5,3=a']),
      Level(id: 'f13', ja: 'つれあい', en: 'Partners', par: 18, map: [
        '#########',
        '#P....#A#',
        '#.......#',
        '#.......#',
        '#.##....#',
        '#.......#',
        '#########',
      ], doors: ['h5,4,2=a', 'h3,5,3', 'h2,3,2', 'h6,2,2=a', 'v4,3,2']),
      Level(id: 'f14', ja: 'ずれた波', en: 'Out of Step', par: 19, map: [
        '#########',
        '#...#...#',
        '#.....#.#',
        '#.....A.#',
        '#....#..#',
        '#P......#',
        '#.....#.#',
        '#########',
      ], doors: ['v6,4,2', 'v3,1,2', 'v2,4,2', 'h4,3,2=a', 'h3,5,2=a']),
      Level(id: 'f15', ja: '大広間', en: 'The Great Hall', par: 21, map: [
        '#########',
        '#.......#',
        '#.#.....#',
        '#...#...#',
        '#.....A.#',
        '#P....B.#',
        '#.....#.#',
        '#########',
      ], doors: ['h3,5,2', 'v5,4,2', 'v7,4,3', 'h4,1,2', 'h4,2,2=a', 'h1,1,2=a']),
      Level(id: 'f16', ja: '波間', en: 'Between the Waves', par: 20, map: [
        '#########',
        '#.....A.#',
        '#..#....#',
        '#.......#',
        '#P...#..#',
        '#.......#',
        '#..#....#',
        '#########',
      ], doors: ['h3,5,2=a', 'v2,4,2', 'h6,4,2', 'h5,3,2', 'v4,3,2', 'h2,1,2=a']),
    ],
  ),
  Chapter(
    number: 3,
    id: 'lock',
    icon: 'lock',
    titleJa: '女将さんの鍵',
    titleEn: 'The Landlady\'s Key',
    subJa: '錠のついたふすまは、鍵を拾うまで動かない。',
    subEn: 'Locked doors stay put until you find the key.',
    levels: [
      Level(id: 'f17', ja: '帳場の鍵', en: 'Key at the Desk', par: 10, map: [
        '#######',
        '#....A#',
        '#.....#',
        '#.#...#',
        '#.#...#',
        '#P..k.#',
        '#######',
      ], doors: ['v3,3,2*', 'v1,2,2', 'h4,4,2']),
      Level(id: 'f18', ja: '遠回り', en: 'The Long Way Round', par: 12, map: [
        '########',
        '#....#.#',
        '#k...#.#',
        '#.....A#',
        '#P.....#',
        '#......#',
        '########',
      ], doors: ['v4,3,2*', 'h2,1,2', 'h3,5,2']),
      Level(id: 'f19', ja: '錠前', en: 'The Lock', par: 14, map: [
        '########',
        '#.#....#',
        '#.#...A#',
        '#P#....#',
        '#.k....#',
        '#......#',
        '########',
      ], doors: ['v5,3,2', 'h4,1,2*', 'v4,2,3', 'h3,5,2']),
      Level(id: 'f20', ja: '鍵が先', en: 'Key First', par: 16, map: [
        '########',
        '#P.....#',
        '#k.....#',
        '#......#',
        '#..#.A.#',
        '#...#..#',
        '#....B.#',
        '########',
      ], doors: ['h4,2,3', 'v6,5,2', 'h3,1,2', 'h2,3,2*']),
      Level(id: 'f21', ja: '寄り道', en: 'A Detour', par: 16, map: [
        '#########',
        '#..#....#',
        '#.......#',
        '#P.#....#',
        '#..#..A.#',
        '#k......#',
        '#########',
      ], doors: ['h5,5,2', 'v7,3,2*', 'h3,2,2', 'h4,4,2', 'h5,3,2']),
      Level(id: 'f22', ja: '蔵の前', en: 'By the Storehouse', par: 20, map: [
        '#########',
        '#.......#',
        '#k......#',
        '#.#.....#',
        '#.#.....#',
        '#.#...A.#',
        '#P......#',
        '#########',
      ], doors: ['h4,6,2*', 'h5,2,2', 'v5,3,3', 'h2,2,2', 'h3,1,3']),
      Level(id: 'f23', ja: '夜番', en: 'Night Watch', par: 19, map: [
        '#########',
        '#.......#',
        '#P.....A#',
        '#...#.#.#',
        '#......B#',
        '#k.#....#',
        '#.......#',
        '#########',
      ], doors: ['v2,3,3', 'v3,2,2', 'h2,6,2', 'h3,1,2', 'v5,2,2*']),
      Level(id: 'f24', ja: '女将さんの部屋', en: 'The Landlady\'s Room', par: 21, map: [
        '#########',
        '#.......#',
        '#.k.....#',
        '#P..#.A.#',
        '#...#.#.#',
        '#.......#',
        '#.......#',
        '#########',
      ], doors: ['v5,2,2', 'h6,6,2', 'h6,2,2', 'h5,5,2*', 'v3,3,3', 'h4,1,2']),
    ],
  ),
  Chapter(
    number: 4,
    id: 'revolve',
    icon: 'revolve',
    titleJa: '回り障子',
    titleEn: 'Revolving Shoji',
    subJa: '柱を軸にくるりと回る障子。横から押すと90度まわる。',
    subEn: 'Shoji that turn on a post: push from the side for a quarter turn.',
    levels: [
      Level(id: 'f25', ja: 'くるり', en: 'Round It Goes', par: 8, map: [
        '#######',
        '#P....#',
        '#.#...#',
        '#.....#',
        '#.....#',
        '#.#..A#',
        '#######',
      ], doors: ['r2,3,l', 'v3,1,2']),
      Level(id: 'f26', ja: '回る柱', en: 'The Turning Post', par: 10, map: [
        '#######',
        '#P#..A#',
        '#...#.#',
        '#.....#',
        '#.....#',
        '#.....#',
        '#######',
      ], doors: ['r1,4,r', 'h4,4,2', 'v3,2,2']),
      Level(id: 'f27', ja: '茶室', en: 'The Tea Room', par: 12, map: [
        '########',
        '#.#..A.#',
        '#......#',
        '#P.....#',
        '#..#...#',
        '#......#',
        '########',
      ], doors: ['r5,3,d', 'v4,3,2', 'h3,5,2', 'v2,2,2']),
      Level(id: 'f28', ja: '二本の柱', en: 'Two Posts', par: 13, map: [
        '########',
        '#......#',
        '#......#',
        '#....#.#',
        '#P....A#',
        '#....#.#',
        '########',
      ], doors: ['r2,4,r', 'r3,1,l', 'h3,2,2', 'v4,3,2']),
      Level(id: 'f29', ja: '中庭', en: 'The Courtyard', par: 16, map: [
        '########',
        '#P.#..A#',
        '#...#..#',
        '#....#.#',
        '#......#',
        '#.....B#',
        '#......#',
        '########',
      ], doors: ['r4,5,d', 'v2,1,2', 'v3,2,2', 'v3,4,2', 'v1,3,2']),
      Level(id: 'f30', ja: '風車', en: 'Pinwheel', par: 16, map: [
        '#########',
        '#.#...#.#',
        '#P......#',
        '#.....A.#',
        '#.......#',
        '#..#....#',
        '#########',
      ], doors: ['r6,5,l', 'r4,3,r', 'h3,2,2', 'h3,4,2', 'h2,3,2']),
      Level(id: 'f31', ja: 'からくり', en: 'Clockwork', par: 21, map: [
        '#########',
        '#.......#',
        '#.......#',
        '#...#..A#',
        '#.......#',
        '#.#...#.#',
        '#P......#',
        '#########',
      ], doors: ['r3,3,d', 'r3,2,r', 'h2,6,2', 'h5,4,2', 'h4,1,2', 'v5,2,2']),
      Level(id: 'f32', ja: '回り廊下', en: 'The Winding Hall', par: 21, map: [
        '#########',
        '#.....B.#',
        '#P..##.A#',
        '#.......#',
        '#....#..#',
        '#.......#',
        '#.......#',
        '#########',
      ], doors: ['r2,4,l', 'r2,3,r', 'v7,5,2', 'h2,6,3', 'h4,3,3', 'h4,1,2']),
    ],
  ),
  Chapter(
    number: 5,
    id: 'mix',
    icon: 'mix',
    titleJa: '宴会の夜',
    titleEn: 'Banquet Night',
    subJa: '総仕上げ。しかけが勢ぞろいの、夜の大宴会。',
    subEn: 'The finale: every trick in the house, on banquet night.',
    levels: [
      Level(id: 'f33', ja: '宴のしたく', en: 'Setting Up', par: 15, map: [
        '########',
        '#P..#..#',
        '#......#',
        '#......#',
        '#k...A.#',
        '#..#...#',
        '########',
      ], doors: ['h3,4,2=a', 'v6,3,2*', 'h4,3,2=a', 'v2,3,2']),
      Level(id: 'f34', ja: '回る波', en: 'Turning Tide', par: 15, map: [
        '########',
        '#......#',
        '#......#',
        '#.....A#',
        '#.##...#',
        '#P.....#',
        '########',
      ], doors: ['r2,3,l', 'v4,2,2', 'h4,4,2=a', 'h3,5,2=a', 'h4,1,2']),
      Level(id: 'f35', ja: '鍵と柱', en: 'Key and Post', par: 14, map: [
        '########',
        '#......#',
        '#..#.#.#',
        '#P...#.#',
        '#.....A#',
        '#.k....#',
        '#......#',
        '########',
      ], doors: ['r1,2,r', 'v4,3,2', 'v6,5,2', 'v3,5,2', 'h3,1,2*']),
      Level(id: 'f36', ja: 'ふた組の宴', en: 'Two Tables', par: 16, map: [
        '#########',
        '#.......#',
        '#.......#',
        '#......A#',
        '#....#..#',
        '#..#....#',
        '#Pk.#.B.#',
        '#########',
      ], doors: ['v2,1,2', 'h2,4,2', 'h3,3,2=a', 'h3,2,2=a', 'v1,4,2*']),
      Level(id: 'f37', ja: '月見', en: 'Moon Viewing', par: 19, map: [
        '#########',
        '#..#...A#',
        '#.......#',
        '#....#B.#',
        '#.......#',
        '#P......#',
        '#....#..#',
        '#########',
      ], doors: ['r5,5,u', 'v7,4,2=a', 'v6,1,2', 'v1,3,2=a', 'v4,3,2', 'h1,1,2']),
      Level(id: 'f38', ja: '蔵座敷', en: 'The Storehouse Parlour', par: 14, map: [
        '#########',
        '#...#...#',
        '#.....#A#',
        '#.......#',
        '#.......#',
        '#..k....#',
        '#P...#..#',
        '#########',
      ], doors: ['r4,5,d', 'r4,2,d', 'h2,4,2*', 'v1,3,3', 'v6,4,2', 'h6,1,2']),
      Level(id: 'f39', ja: '大詰め', en: 'The Home Stretch', par: 23, map: [
        '#########',
        '#...#...#',
        '#P#.....#',
        '#.#.....#',
        '#.......#',
        '#.k.....#',
        '#....#A.#',
        '#########',
      ], doors: ['r5,2,r', 'h2,6,2=a', 'v1,4,2', 'v7,3,2*', 'h5,4,2=a', 'v4,4,2']),
      Level(id: 'f40', ja: 'お開き', en: 'Last Orders', par: 24, map: [
        '#########',
        '#..#....#',
        '#......A#',
        '#k...#B.#',
        '#..#..#.#',
        '#P......#',
        '#.......#',
        '#########',
      ], doors: ['r4,1,d', 'v7,3,3', 'h2,6,2', 'h2,5,2=a', 'v2,2,2*', 'h5,1,2=a', 'v4,4,2']),
    ],
  ),
];

final List<Level> allLevels = linkLevels(chapters);

Level? levelById(String id) {
  for (final l in allLevels) {
    if (l.id == id) return l;
  }
  return null;
}
